version: '3.8'
services:
  chronos:
    build: .
    privileged: true
    environment:
      - DISPLAY=:99
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    shm_size: 2gb
    entrypoint: /app/entrypoint.sh
